
- name: Set Up YUM Repos 
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash


- name: Install ERLANG and RabbitMQ 
  ansible.builtin.yum: 
    name: 
      - https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
      - rabbitmq-server
    state: installed 

- name: Starting {{COMPONENT}} Service 
  ansible.builtin.systemd:
    name: "{{COMPONENT}}-server" 
    state: started 
    enabled: yes

- name: Adding {{COMPONENT}} App User  
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: Configuing system name 
  ansible.builtin.include_role:
    name: common 
    tasks_from: set-hostname